### PR TITLE
Fallback just in case minifyer is not there

### PR DESCRIPTION
**Pull request by DO1JLR**

### CODE REVIEW

**Comment by maxbachmann** [comment]
this will not work at least for toolbox-bodensee, since unminified js files and scss files are not used by lektor:
https://github.com/ToolboxBodensee/toolbox-webseite/blob/master/toolbox-webseite.lektorproject

**Comment by DO1JLR** [comment]
why?

This is checking **if** there is an minified file.

If there is none, it will try to use an unminified.

Otherwise it will use the minified.

It will always use the minified first. the other is only a fallback, if it is not available!

I guess it won't hurt to have more fallbacks...

**Comment by maxbachmann** [comment]
What I mean is that at least on the toolbox website the unminified version can not exist. Yes it will not destroy anything since it will just always check if there is the minified version and if it does not exist check for the unminified version and then still fail
Just wanted to mention that for the toolbox website it is the equivalent to:
```python
if Path(x).exists():
elif False:
```
since the unminified version are excluded using `excluded_assets`

**Comment by DO1JLR** [comment]
Die Idee eines Themes wäre ja, es an mehreren Orten gleichzeitig zu verwenden ``;-)``

**Comment by maxbachmann** [comment]
ja daher merke ich an, dass das zumindest dort nicht funktioniert und ob es bei den anderen Webseiten mal funktionieren wird kannst nur du wissen :)
Wenn es das tut habe ich damit kein grundsätzliches Problem

**Pull request merged**
